<a href="https://colab.research.google.com/github/ryueuitae-blip/AIEYES-STUDY/blob/euitae-branch/numpy-code%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# numpy: 행렬, 다차원 배열 연산
import numpy as np # numpy 모듈 불러오기, 이제 np로 부름

In [ ]:
data = [1,2,3,4]
result= []

for i in data: # data 리스트 안의 i에 대한 반복문
  result.append(i*10) # result 라는 리스트에 i에 10을 곱해서 들어간다

print(result)

[10, 20, 30, 40]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4]) # list 타입을 다차원 배열로
arr10 = arr * 10 # 위에서와 달리 반복문 필요X

print(arr10)

[10 20 30 40]


In [ ]:
import numpy as np

In [ ]:
data = [1, 2, 3, 4]
data * 10

[1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4]

In [ ]:
arr = np.array(data) # 리스트를 numpy 배열로 변환하여, arr 변수에 할당

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
type(arr) # ndarray: numpy-dimensional array

numpy.ndarray

In [ ]:
type(data)

list

In [ ]:
price = [             # 중첩 리스트
[100, 80, 70, 90],  # 첫 번째 행
[120, 110, 100, 110] # 두 번째 행
]
print(price[0]) # 인덱싱을 이용해서는 행만 불러올수 있음

arr2 = np.array(price) # 리스트에서 ndarray 타입으로 변경

[100, 80, 70, 90]


In [ ]:
data = [
    [10,20,30,40],
    [1,2,3,4,]
    ]

In [ ]:
type(data)

list

In [ ]:
data[0]

[10, 20, 30, 40]

In [ ]:
arr = np.array(data)

In [ ]:
arr # 2차원 표현

array([[10, 20, 30, 40],
       [ 1,  2,  3,  4]])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr[0] # 넘파이 인덱싱 0번째 행

array([10, 20, 30, 40])

In [ ]:
arr[1] # 1번째 행

array([1, 2, 3, 4])

In [ ]:
arr[0][0] # 넘파이의 64비트 정수 자료형

np.int64(10)

In [ ]:
arr[0][3]

np.int64(40)

In [ ]:
arr

array([[10, 20, 30, 40],
       [ 1,  2,  3,  4]])

In [ ]:
arr[:, 0]

array([10,  1])

In [ ]:
arr[:,1]

array([20,  2])