<a href="https://colab.research.google.com/github/ryueuitae-blip/AIEYES-STUDY/blob/ryu/01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#NumPy
#행렬이나 다차원 배열 연산 지원

In [11]:
#임포트(with 별칭)
import numpy as np

In [25]:
#파이썬 리스트는...
data = [1,2,3,4]
data * 10 #값에 곱연산을 수행하는게 아니라 반복으로 인식

[1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4,
 1,
 2,
 3,
 4]

In [26]:
#반복문을 활용하면 해결은 가능.. 하지만 불편함

data = [1,2,3,4]
result = []

for i in data:
    result.append(i * 10)

print(result)

[10, 20, 30, 40]


In [ ]:
#numpy를 사용하여 배열 arr 생성
arr = np.array(data)

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
type(arr) #리스트에서 ndarray라는 타입으로 변경된 것을 확인

numpy.ndarray

In [ ]:
arr * 10 #리스트와 달리 값의 배수로 인식 -> 다차원 행렬, 배열 처리에 용이

array([10, 20, 30, 40])

In [23]:
#2차원 데이터 다루기
#리스트의 한계 -> 열 단위 접근 불가(행 단위만 가능, 리스트는 범용적 목적이므로 transpose 등 행렬 특화 연산 지원 X)

data = [
    [1,2,3,4],
    [10,20,30,40]
]

print(data[1]) # 행 단위...
print(data[1][3]) # 요소 단위...
#print(data[][1]) <- 열 단위? 이런건 당연히 안된다

[10, 20, 30, 40]
40


In [13]:
type(data)

list

In [14]:
arr = np.array(data)

In [15]:
data[0] #인덱스를 활용한 행 단위 접근

[1, 2, 3, 4]

In [16]:
type(arr)

numpy.ndarray

In [17]:
arr[0]

array([1, 2, 3, 4])

In [18]:
arr[1]

array([10, 20, 30, 40])

In [19]:
arr[0][1] #numpy의 64bit 정수형 값

np.int64(2)

In [ ]:
arr[0,0]

np.int64(1)

In [ ]:
arr[:,0] #모든 행에 대해 첫째 열 값을 가져올 것

array([ 1, 10])

In [ ]:
arr[:,:] #행도 열도 지정되지 않아 다 가져옴

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])