In [7]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 5.3 MB 10.8 MB/s eta 0:00:01
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [ ]:
import numpy as np

arr= np.array([1,2,3,4])
arr10 = arr * 10

print(arr10)

[10 20 30 40]


In [21]:
price = [
    [100,80,70,90],
    [120,110,100,110]
]
print(price[0])

[100, 80, 70, 90]


In [23]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 10.8 MB 10.0 MB/s eta 0:00:01
     |████████████████████████████████| 510 kB 35.5 MB/s eta 0:00:01
     |████████████████████████████████| 348 kB 115.9 MB/s eta 0:00:01
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [24]:
import pandas as pd


In [25]:
from pandas import Series
arr = [0,1,2,3]
s = Series(arr)
print(s)

0    0
1    1
2    2
3    3
dtype: int64


In [26]:
data = [100,200,300]
s = Series(data)
print(s)

0    100
1    200
2    300
dtype: int64


In [28]:
datadata = [100,200,300]
index = ["월","화","수"]
s = Series(data,index)
print(s)

월    100
화    200
수    300
dtype: int64


In [29]:
datadata = [100,200,300]
index = ["월","화","수"]
s = Series(data,index)
print(s.index)
print(s.values)

Index(['월', '화', '수'], dtype='object')
[100 200 300]


In [30]:
s.array

<NumpyExtensionArray>
[100, 200, 300]
Length: 3, dtype: int64

In [32]:
data = [500,800,200]
index = ("메로나","누가바","빠삐코")
s = pd.Series(data,index)
print(s.index)
print(s.values)

Index(['메로나', '누가바', '빠삐코'], dtype='object')
[500 800 200]
