In [7]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 5.3 MB 10.8 MB/s eta 0:00:01
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [11]:
import numpy as np

arr= np.array([1,2,3,4])
arr10 = arr * 10

print(arr10)

[10 20 30 40]


In [21]:
price = [
    [100,80,70,90],
    [120,110,100,110]
]
print(price[0])

[100, 80, 70, 90]


In [23]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 10.8 MB 10.0 MB/s eta 0:00:01
     |████████████████████████████████| 510 kB 35.5 MB/s eta 0:00:01
     |████████████████████████████████| 348 kB 115.9 MB/s eta 0:00:01
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [24]:
import pandas as pd


In [2]:
from pandas import Series
arr = [0,1,2,3]
s = Series(arr)
print(s)

0    0
1    1
2    2
3    3
dtype: int64


In [3]:
data = [100,200,300]
s = Series(data)
print(s)

0    100
1    200
2    300
dtype: int64


In [5]:
datadata = [100,200,300]
index = ["월","화","수"]
s = Series(data,index)
print(s)

월    100
화    200
수    300
dtype: int64


In [29]:
datadata = [100,200,300]
index = ["월","화","수"]
s = Series(data,index)
print(s.index)
print(s.values)

Index(['월', '화', '수'], dtype='object')
[100 200 300]


In [30]:
s.array

<NumpyExtensionArray>
[100, 200, 300]
Length: 3, dtype: int64

In [15]:
data = [500,800,200]
index = ("메로나","누가바","빠삐코")
s = pd.Series(data,index)
print(s.index)
print(s.values)

NameError: name 'pd' is not defined

In [16]:
array = ([[10,20,30,40],
          [1,2,3,4]])

gam = np.array(array)
type(gam)

gam[:,1]

array([20,  2])

In [20]:
#iloc = integer location 
#iloc 속성을 사용하여 인덱싱

import pandas as pd

data = [100,200,300]
index = ["월","화","수"]
s = pd.Series(data,index)
s

월    100
화    200
수    300
dtype: int64

In [21]:
s.iloc[0]

np.int64(100)

In [ ]:
s.iloc[2] 

np.int64(300)

In [24]:
s.iloc[-1] #음수로도 가능 


np.int64(300)

In [ ]:
# 딕셔너리처럼 키 
# 시리즈 객체에서는 인덱스라고 부름
# loc = location 

s.loc["월"]

np.int64(100)

In [26]:
s.loc["화"]

np.int64(200)

In [ ]:
#리스트에서는 [ ] 사용
#시리즈에서도 지원하지만, 잘 안씀...

s[0] #행번호로 해석해서 가져오게돔

/var/folders/3d/v8nt36h54cx01nc5xdcz0gb40000gn/T/ipykernel_26545/926754931.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[0]


np.int64(100)

In [ ]:
#iloc를 활용한 슬라이싱
#시작 행번호 : 끝 행번호
data = [100,200,300]
index = ["월","화","수"]
s = Series(data,index)
print ( s.iloc[0:2]) # 0번째, 첫번째 가져옴 마지막 포함 안됨!!

월    100
화    200
dtype: int64


In [ ]:
#loc를 활용한 슬라이싱
#iloc와의 차이 == 시작 인덱스 : 끝 인덱스가 포함이 됨!!!
data = [100,200,300]
index = ["월","화","수"]
s = Series(data,index)
print ( s.loc["월":"화"])

월    100
화    200
dtype: int64


In [ ]:
#여러 값 인덱싱 / 멀티인덱싱
#파이썬과 달리 연속적이지 않은데 여러값을 가져올수있음 
#iloc loc 둘다 가능 
#[0,2]
#0번과 2번을 가져오겠다는 뜻 

s.iloc[[0,2]] #[]안에 다시 [] 사용 

월    100
수    300
dtype: int64

In [ ]:
s.loc[["월","수"]] #iloc, loc 사용 권장 

월    100
수    300
dtype: int64